language: swift
osx_image: xcode9
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LIB_PROJECT=Logging.xcodeproj
  matrix:
    include:
      - env: JOB="POD_LINT"
        script:
        - pod lib lint
      - env: PROJECT_FILE="$LIB_PROJECT"       DESTINATION="OS=10.3.1,name=iPhone 7"             SCHEME="Logging-iOS"                SDK="iphonesimulator"        BUILDCMD="clean test build"
      - env: PROJECT_FILE="$LIB_PROJECT"       DESTINATION="OS=10.0,name=Apple TV 1080p"         SCHEME="Logging-tvOS"               SDK="appletvsimulator"       BUILDCMD="clean test build" 
      - env: PROJECT_FILE="$LIB_PROJECT"       DESTINATION="OS=3.2,name=Apple Watch - 42mm"      SCHEME="Logging-watchOS"            SDK="watchsimulator"         BUILDCMD="clean build" 
      - env: PROJECT_FILE="$LIB_PROJECT"       DESTINATION="arch=x86_64"                         SCHEME="Logging-macOS"              SDK="macosx"                 BUILDCMD="clean test build"  
  script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT_FILE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ENABLE_TESTABILITY=YES $BUILDCMD | xcpretty -c;
notifications:
  email:
    on_success: never